# Generated by Django 5.1.2 on 2024-11-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecipeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_author", models.CharField(max_length=75)),
                ("recipe_name", models.CharField(max_length=75)),
                ("recipe_type", models.CharField(max_length=15)),
                ("ingredients_needed", models.CharField(max_length=600)),
                ("recipe_instructions", models.CharField(max_length=1200)),
                ("prep_time", models.IntegerField(blank=True, null=True)),
                ("cooking_temp", models.IntegerField(blank=True, null=True)),
                ("servings", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
