# Generated by Django 5.1.2 on 2024-11-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipedata",
            name="recipe_type",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
