# Generated by Django 5.1.2 on 2024-11-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_recipedata_recipe_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipedata",
            old_name="prep_time",
            new_name="prep_time_in_hours",
        ),
        migrations.AddField(
            model_name="recipedata",
            name="prep_time_in_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
