# Generated by Django 5.1.2 on 2024-11-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_prep_time_recipedata_prep_time_in_hours_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_author", models.CharField(max_length=75)),
                ("recipe_name", models.CharField(max_length=75)),
                ("recipe_type", models.CharField(blank=True, max_length=15, null=True)),
                ("ingredients_needed", models.CharField(max_length=600)),
                ("recipe_instructions", models.CharField(max_length=1200)),
                ("prep_time_in_minutes", models.IntegerField(blank=True, null=True)),
                ("prep_time_in_hours", models.IntegerField(blank=True, null=True)),
                ("cooking_temp", models.IntegerField(blank=True, null=True)),
                ("servings", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
