# Generated by Django 5.1.2 on 2024-11-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_savedrecipe_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrecipe",
            name="feedback",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
